force-app/main/default/objects/osf_Image__c/osf_Image__c.object-meta.xml
<CustomObject>
    <label>osf Image</label>
    <nameField>
        <label>osf Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>osf Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/osf_Image__c/fields/osf_base64__c.field-meta.xml
<CustomField>
    <fullName>osf_base64__c</fullName>
    <label>osf base64</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/osf_Image.cls
public with sharing class osf_Image {
    public String getBase64String() {
        osf_Image__c sr = [SELECT id, osf_base64__c
                           FROM osf_Image__c
                           WHERE Name = 'image2']; // external service call

        return sr.osf_base64__c;
    }

    /*
    public String getBase64String() {
        StaticResource sr = [SELECT body
                             FROM StaticResource
                             WHERE Name = 'base64image']; // external service call
        String stringFileContent = sr.body.toString();

        return stringFileContent;
    }
     */
}