force-app/main/default/objects/osf_Account_Mapping__mdt/osf_Account_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>osf Account Mapping</label>
    <pluralLabel>osf Accounts Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Active__c.field-meta.xml
<CustomField>
    <fullName>osf_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>osf Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Email__c.field-meta.xml
<CustomField>
    <fullName>osf_Email__c</fullName>
    <label>osf Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Fields_Map__c.field-meta.xml
<CustomField>
    <fullName>osf_Fields_Map__c</fullName>
    <label>osf Fields Map</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Last_Value__c.field-meta.xml
<CustomField>
    <fullName>osf_Last_Value__c</fullName>
    <label>osf Last Value</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Target_Object__c.field-meta.xml
<CustomField>
    <fullName>osf_Target_Object__c</fullName>
    <label>osf Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Unique_Field__c.field-meta.xml
<CustomField>
    <fullName>osf_Unique_Field__c</fullName>
    <label>osf Unique Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/osf_AccountSourceService.cls
public with sharing class osf_AccountSourceService {
    // TODO: check if a custom metadata type can be abstracted and revise all methods here
    public static osf_Account_Mapping__mdt getCustomSettings() {
        osf_Account_Mapping__mdt settings;
        
        for(osf_Account_Mapping__mdt rec: [
            SELECT Id, DeveloperName, MasterLabel, NamespacePrefix, osf_Active__c, osf_Last_Value__c, osf_Email__c, osf_Target_Object__c, osf_Fields_Map__c, osf_Unique_Field__c
            FROM osf_Account_Mapping__mdt
            WHERE osf_Active__c = true
            ORDER BY osf_Last_Value__c DESC
            LIMIT 1
        ]) {
            settings = rec;
        }

        return settings;
    }

    public static Map<String, Object> getFieldsMap(osf_Account_Mapping__mdt settings) {
        String fieldsMapJsonString = settings.osf_Fields_Map__c;
        Map<String, Object> fieldsMap = (Map<String, Object>) JSON.deserializeUntyped(fieldsMapJsonString);

        return fieldsMap;
    }

    public static Schema.SObjectField getUniqueField(osf_Account_Mapping__mdt settings) {
        SObject targetSObj = Schema.getGlobalDescribe().get(settings.osf_Target_Object__c).newSObject();
        Schema.SObjectField uniqueField = targetSObj.getSObjectType().getDescribe().fields.getMap().get(settings.osf_Unique_Field__c);
        
        return uniqueField;
    }
}