force-app/main/default/objects/osf_Account_Mapping__mdt/osf_Account_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>osf Account Mapping</label>
    <pluralLabel>osf Accounts Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Active__c.field-meta.xml
<CustomField>
    <fullName>osf_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>osf Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Email__c.field-meta.xml
<CustomField>
    <fullName>osf_Email__c</fullName>
    <label>osf Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/osf_Account_Mapping__mdt/fields/osf_Last_Value__c.field-meta.xml
<CustomField>
    <fullName>osf_Last_Value__c</fullName>
    <label>osf Last Value</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/osf_Account_Source__c/osf_Account_Source__c.object-meta.xml
<CustomObject>
    <label>osf Account Source</label>
    <nameField>
        <label>osf Account Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>osf Accounts Source</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/osf_Account_Source__c/fields/osf_Source_Number__c.field-meta.xml
<CustomField>
    <fullName>osf_Source_Number__c</fullName>
    <label>osf Source Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/osf_AccountIntegrationService.cls
global class osf_AccountIntegrationService implements Database.Batchable<sObject>, Database.Stateful {
    // instance members to retain state across transactions
    global Integer recordsProcessed = 0;
    global osf_Account_Mapping__mdt accountMapping;
    global Datetime newLastValue;
    
    public osf_AccountIntegrationService() {

    }

    // collect the batches of records or objects to be passed to execute
    // return (Database.QueryLocator | Iterable<sObject>)
    global Database.QueryLocator start(Database.BatchableContext bc) {
        for(osf_Account_Mapping__mdt rec: [
            SELECT Id, osf_Active__c, osf_Last_Value__c, osf_Email__c
            FROM osf_Account_Mapping__mdt
            WHERE osf_Active__c = true
            ORDER BY osf_Last_Value__c DESC
            LIMIT 1
        ]) {
            accountMapping = rec;
        }

        // TODO: handle when there is no metadata returned
        return Database.getQueryLocator([
            SELECT Name, LastModifiedDate, osf_Source_Number__c, osf_Codigo_Cobra__c
            FROM osf_Account_Source__c
            WHERE LastModifiedDate > :accountMapping.osf_Last_Value__c
        ]);
    }

    // TODO: process each batch of records
    global void execute(Database.BatchableContext bc, List<osf_Account_Source__c> scope) {
        if(scope.size() > 0) {
            List<osf_Account_Source__c> newAccounts = new List<osf_Account_Source__c>();

            for(osf_Account_Source__c account: scope) {
                account.osf_Source_Number__c = 13;
                recordsProcessed = recordsProcessed + 1;
                newAccounts.add(account);
                
                if(account.LastModifiedDate > newLastValue || newLastValue == null) {
                    newLastValue = account.LastModifiedDate;
                }
            }

            upsert newAccounts;
        }
    }

    // execute any post-processing operations
    global void finish(Database.BatchableContext bc) {
        AsyncApexJob job = [
            SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()
        ];

        osf_MessageService.sendEmailMessageByJob(job, accountMapping, recordsProcessed);
        
        if(job.Status == 'Completed' && job.NumberOfErrors == 0 && recordsProcessed > 0) {
            // TODO: update osf_Last_Value__c on metadata

            // accountMapping.osf_Last_Value__c = newLastValue;
            // upsert accountMapping;

            // HandleMetadata handleMetadata = new HandleMetadata();
            // handleMetadata.updateAndDeployMetadata(newLastValue);
        }
    }
}